### PR TITLE
Remove panics

### LINKED ISSUE #29: Panics in helper functions
Helper packages usually don't panic when something bad happens, they just return errors so the user can decide what to do with it.

**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

### PR DESCRIPTION
**Pull request by bshramin**
Fixes #29  

#### PR Checklist

- [ ] Tests
- [ ] Passing Pipeline
- [ ] Documentation

### CODE REVIEW

File: elastic/elastic.go [hunk 1]
```diff
@@ -21,13 +20,8 @@ func GetConnection(host string, port int) *elastic.Client {
 			Transport: elasticsearch.WrapRoundTripper(http.DefaultTransport),
 		}),
 	)
-	if err != nil {
-		logrus.Error("connect to elastic failed")
-		panic(err)
-	}
 
-	logrus.Infof("successfully connected to elastic : %s", connection)
```
Comment (shahabeshaghi67) [inline elastic/elastic.go:29]: why did you deleted infos

**Review by mahdimakki — APPROVED** [review]

File: elastic/elastic.go (hunk 1 above)
Comment (bshramin) [reply elastic/elastic.go:29]: these helper functions only return errors to the caller, caller decides if there are no errors whether to log a success message or not, as described in #29 .

**Review by shahabeshaghi67 — APPROVED** [review]
